// apps/vue-inzforge/src/app/components/PageHeadline.vue
<template>
  <h1 class="text-inz-3xl font-bold mb-inz-3 text-inz-foreground">
    {{ title || "UNSPECIFIED HEADLINE TITLE" }}
  </h1>
  <h3 v-if="subtitle" class="text-inz-lg font-light text-inz-muted-foreground mt-inz-1 mb-inz-3">
    {{ subtitle }}
  </h3>
</template>

<script lang="ts" setup>
defineProps<{
  title?: string;
  subtitle?: string;
}>();
</script>

// apps/angular-inzforge/src/app/shared/components/page-headline/page-headline.component.ts
import {Component, input} from "@angular/core";

@Component({
  selector: "inz-app-page-headline",
  standalone: true,
  template: `
    <h1 class="text-inz-3xl font-bold mb-inz-3 text-inz-foreground">{{ title() || "UNSPECIFIED HEADLINE TITLE" }}</h1>
    @if (!!subtitle()) {
      <h3 class="text-inz-lg font-light text-inz-muted-foreground mt-inz-1 mb-inz-3">{{ subtitle() }}</h3>
    }
  `
})
export class InzAppPageHeadlineComponent {
  title = input<string>("");
  subtitle = input<string | undefined>(undefined);
}
