// apps/vue-inzforge/src/app/components/ShowcaseContainer.vue
<template>
  <div
    :class="{ 'bg-inz-foreground': isDarkModeOn }"
    :dir="isRtlDirection ? 'rtl' : 'ltr'"
    class="p-inz-10 border-2 inz-border rounded-inz-md bg-inz-background transition-colors duration-300"
  >
    <slot></slot>
  </div>
</template>

<script lang="ts" setup>
import {useShowcaseContainer} from '../composables/useShowcaseContainer';

const {isRtlDirection, isDarkModeOn} = useShowcaseContainer();
</script>

// apps/angular-inzforge/src/app/shared/components/showcase-container/showcase-container.component.ts
import {Component, inject} from "@angular/core";
import {InzForgeAppShowcaseContainerService} from "./showcase-container.service";

@Component({
  selector: "inz-app-component-showcase-container",
  standalone: true,
  template: `
    <div
      class="p-inz-10 border-2 inz-border rounded-inz-md bg-inz-background transition-colors duration-300"
      [class.bg-inz-foreground]="this.myService.isDarkModeOn()"
      [attr.dir]="this.myService.isRtlDirection() ? 'rtl' : 'ltr'">

      <ng-content></ng-content>

    </div>
  `
})
export class InzForgeAppShowcaseContainerComponent {
  protected myService = inject(InzForgeAppShowcaseContainerService);
}
