// apps/vue-inzforge/src/app/components/Sidebar.vue
<template>
  <div class="fixed inset-y-0 left-0 z-inz-sticky w-64 bg-inz-background border-r border-inz-border">
    <div class="h-full overflow-y-auto pt-inz-4 px-inz-6">
      <h3 class="text-inz-xl font-semibold mb-inz-4">Content</h3>
      <ul class="list-none p-0 m-0 flex flex-col space-y-inz-1">
        <li v-for="item in menuItems" :key="item.path">
          <router-link
            :class="{ '!bg-inz-secondary !text-inz-accent-foreground': isActive(item.path) }"
            :to="item.path"
            class="flex items-center w-full py-inz-2 px-inz-3 font-medium text-inz-foreground rounded-inz-md transition-colors duration-inz-normal hover:bg-inz-muted"
          >
            <span class="whitespace-nowrap overflow-hidden text-ellipsis">{{ item.label }}</span>
          </router-link>

          <!-- Render child items if they exist -->
          <ul
            v-if="item.children && item.children.length > 0"
            class="list-none p-0 m-0 pt-inz-2 flex flex-col space-y-inz-1 ml-inz-4"
          >
            <li v-for="child in item.children" :key="child.path">
              <router-link
                :to="child.path"
                active-class="bg-inz-secondary text-inz-accent-foreground"
                class="flex items-center w-full py-inz-2 px-inz-3 text-inz-sm font-medium rounded-inz-md transition-colors duration-inz-normal hover:bg-inz-muted"
              >
                <span class="whitespace-nowrap overflow-hidden text-ellipsis">{{ child.label }}</span>
              </router-link>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts" setup>
import {computed, onMounted} from 'vue';
import {useRoute, useRouter} from 'vue-router';

interface MenuItem {
  label: string;
  path: string;
  children?: MenuItem[];
}

const route = useRoute();
const router = useRouter();

// Define menu items based on the router configuration
const menuItems = computed<MenuItem[]>(() => {
  return [
    {
      label: 'Home',
      path: '/',
    },
    {
      label: 'HyperUI',
      path: '/hyperui',
      children: [
        {
          label: 'Accordion',
          path: '/hyperui/accordion',
        }
      ]
    }
  ];
});

const isActive = (path: string) => {
  return route.path === path;
};

onMounted(() => {
  // Any initialization logic if needed
});
</script>

// apps/angular-inzforge/src/app/shared/components/app-sidebare/sidebar.component.ts
import {Component, OnInit, signal} from '@angular/core';
import {NavigationEnd, Route, Router, RouterModule} from '@angular/router';
import {filter} from 'rxjs/operators';

interface MenuItem {
  label: string;
  path: string;
  children?: MenuItem[];
}

@Component({
  selector: 'inz-app-sidebar',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class InzForgeAppSidebarComponent implements OnInit {
  menuItems = signal<MenuItem[]>([]);

  constructor(private router: Router) {
    this.generateMenuItems();
  }

  ngOnInit() {
    this.generateMenuItems();

    // Listen for route changes to update the menu if needed
    this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe(() => {
        this.generateMenuItems();
      });
  }

  isActive(path: string): boolean {
    return this.router.url === path;
  }

  private generateMenuItems() {
    // Extract routes from the router configuration
    const routes = this.router.config;
    const items = this.processRoutes(routes);
    this.menuItems.set(items);
  }

  private processRoutes(routes: Route[], basePath: string = ''): MenuItem[] {
    const menuItems: MenuItem[] = [];

    for (const route of routes) {
      // Skip routes that have no path or are redirects
      if (route.path == undefined || route.path === '**') continue;

      // Build the full path
      const fullPath = basePath ? `${basePath}/${route.path}` : route.path;

      // Generate a label from the path if no data is provided
      let label = route.data?.['label'] as string || this.pathToLabel(route.path);

      // If it's the root path, set a specific label
      if (fullPath === '') {
        label = 'Home';
      }

      // Create menu item
      const menuItem: MenuItem = {
        label: label,
        path: fullPath === '' ? '/' : `/${fullPath}`
      };

      // Process children if they exist
      if (route.children && route.children.length > 0) {
        menuItem.children = this.processRoutes(route.children, fullPath);
      }

      menuItems.push(menuItem);
    }

    return menuItems;
  }

  private pathToLabel(path: string): string {
    // Convert path to a readable label
    return path
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }
}

<div class="fixed inset-y-0 left-0 z-inz-sticky w-64 bg-inz-background border-r border-inz-border">
  <div class="h-full overflow-y-auto pt-inz-4 px-inz-6">
    <h3 class="text-inz-lg font-semibold mb-inz-4">InzForge UI</h3>
    <ul class="list-none p-0 m-0 flex flex-col space-y-inz-1">
      @for (item of menuItems(); track item.path) {
        <li>
          <a
            class="flex items-center w-full py-inz-2 px-inz-3 font-medium text-inz-foreground rounded-inz-md transition-colors duration-inz-normal hover:bg-inz-muted"
            [routerLink]="item.path"
            [class.!bg-inz-secondary]="isActive(item.path)"
            [class.!text-inz-accent-foreground]="isActive(item.path)">
            <span class="whitespace-nowrap overflow-hidden text-ellipsis">{{ item.label }}</span>
          </a>

          <!-- Render child items if they exist -->
          @if (item.children && item.children.length > 0) {
            <ul
              class="list-none p-0 m-0 pt-inz-2 flex flex-col space-y-inz-1 ml-inz-4">
              @for (child of item.children; track child.path) {
                <li>
                  <a
                    class="flex items-center w-full py-inz-2 px-inz-3 text-inz-sm font-medium rounded-inz-md transition-colors duration-inz-normal hover:bg-inz-muted"
                    [routerLink]="child.path"
                    routerLinkActive="bg-inz-secondary text-inz-accent-foreground">
                    <span class="whitespace-nowrap overflow-hidden text-ellipsis">{{ child.label }}</span>
                  </a>
                </li>
              }
            </ul>
          }
        </li>
      }
    </ul>
  </div>
</div>
